### ISSUE TITLE
Another installation issue

### ISSUE THREAD

**Issue by Chandr01** [wavestone-cdt/abaddon#11]
Digital Ocean debian 10

  Stored in directory: /root/.cache/pip/wheels/41/d7/d3/d064417caaa3073a047b71ff03755d0209f9b2f7d5e61dac97
Successfully built django-datetime-widget django-export-download Events flower future jsonmerge libmagic psycopg2-binary pyhunter tornado python-crontab diff-match-patch
ERROR: awscli 1.18.59 has requirement botocore==1.16.9, but you'll have botocore 1.12.253 which is incompatible.
ERROR: awscli 1.18.59 has requirement s3transfer<0.4.0,>=0.3.0, but you'll have s3transfer 0.2.1 which is incompatible.
ERROR: flower 0.9.3 has requirement tornado<6.0.0,>=4.2.0, but you'll have tornado 6.0.3 which is incompatible.
Installing collected packages: vine, amqp, pytz, Babel, backports-abc, billiard, urllib3, botocore, s3transfer, boto3, zipp, importlib-metadata, kombu, celery, certifi, sqlparse, Django, django-adminlte2, django-timezone-field, python-crontab, django-celery-beat, djangorestframework, django-celery-inspect, django-celery-results, django-datetime-widget, django-debug-toolbar, diff-match-patch, tablib, django-import-export, django-export-download, six, django-extensions, django-formtools, django-tables2, Events, tornado, flower, future, futures, idna, jsonfield, jsonmerge, libmagic, meld3, psycopg2-binary, requests, pyattck, pyhunter, python-magic, python-memcached, singledispatch, thehive4py, Werkzeug
  Attempting uninstall: pytz
    Found existing installation: pytz 2019.3
    Not uninstalling pytz at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pytz'. No files were found to uninstall.
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.25.9
    Not uninstalling urllib3 at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'urllib3'. No files were found to uninstall.
  Attempting uninstall: botocore
    Found existing installation: botocore 1.16.9
    Uninstalling botocore-1.16.9:
      Successfully uninstalled botocore-1.16.9
  Attempting uninstall: s3transfer
    Found existing installation: s3transfer 0.3.3
    Uninstalling s3transfer-0.3.3:
      Successfully uninstalled s3transfer-0.3.3
  Attempting uninstall: certifi
    Found existing installation: certifi 2020.4.5.1
    Not uninstalling certifi at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'certifi'. No files were found to uninstall.
  Attempting uninstall: six
    Found existing installation: six 1.14.0
    Not uninstalling six at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'six'. No files were found to uninstall.
  Attempting uninstall: idna
    Found existing installation: idna 2.9
    Not uninstalling idna at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'idna'. No files were found to uninstall.
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Not uninstalling requests at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'requests'. No files were found to uninstall.
  Attempting uninstall: Werkzeug
    Found existing installation: Werkzeug 1.0.0
    Not uninstalling werkzeug at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'Werkzeug'. No files were found to uninstall.
Successfully installed Babel-2.7.0 Django-2.2.10 Events-0.3 Werkzeug-0.15.5 amqp-2.5.1 backports-abc-0.5 billiard-3.6.1.0 boto3-1.9.214 botocore-1.12.253 celery-4.3.0 certifi-2019.6.16 diff-match-patch-20181111 django-adminlte2-0.4.1 django-celery-beat-1.5.0 django-celery-inspect-0.2.1 django-celery-results-1.1.2 django-datetime-widget-0.9.3 django-debug-toolbar-2.0 django-export-download-0.2.3 django-extensions-2.2.1 django-formtools-2.1 django-import-export-1.2.0 django-tables2-2.1.0 django-timezone-field-4.0 djangorestframework-3.10.2 flower-0.9.3 future-0.17.1 futures-3.1.1 idna-2.8 importlib-metadata-1.6.0 jsonfield-2.0.2 jsonmerge-1.6.1 kombu-4.6.4 libmagic-1.0 meld3-1.0.2 psycopg2-binary-2.8.3 pyattck-1.0.4 pyhunter-1.2 python-crontab-2.4.2 python-magic-0.4.15 python-memcached-1.59 pytz-2018.3 requests-2.22.0 s3transfer-0.2.1 singledispatch-3.4.0.3 six-1.12.0 sqlparse-0.3.0 tablib-1.1.0 thehive4py-1.6.0 tornado-6.0.3 urllib3-1.25.3 vine-1.3.0 zipp-3.1.0
Cloning into '/opt/abaddon/nmaptocsv'...
remote: Enumerating objects: 117, done.                                                                                                                                   
remote: Total 117 (delta 0), reused 0 (delta 0), pack-reused 117                                                                                                          
Receiving objects: 100% (117/117), 47.87 KiB | 357.00 KiB/s, done.
Resolving deltas: 100% (59/59), done.

PATCHING SIX

sed: can't read /root/.local/lib/python3.7/site-packages/datetimewidget/widgets.py: No such file or directory
root@debian-s-1vcpu-1gb-fra1-01:/opt/abaddon#

**Comment by Ibrahimous** [comment]
I can't understand your set up.
Please be more specific.
