### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by microidz** [wavestone-cdt/abaddon#16]
Hi,

I'm trying to install Abaddon on Kali Linux 2020.4 but I keep getting a "chown: cannot access '/var/run/docker.sock': No such file or directory" error message and the installation stops there. Do you have any idea on what could be wrong

And when I check for the file with the root account, it's not there:

root@kali:~/abaddon/setup# cat /var/run/docker.sock
cat: /var/run/docker.sock: No such file or directory

(snip)...

The following NEW packages will be installed:
  cgroupfs-mount{a} containerd{a} containerd.io{b} docker-compose docker.io{a} libintl-perl{a} libintl-xs-perl{a} libmodule-find-perl{a} libmodule-scandeps-perl{a} libproc-processtable-perl{a} libsort-naturally-perl{a} needrestart{a} pigz{a} 
  python3-cached-property{a} python3-docker{a} python3-dockerpty{a} python3-docopt{a} runc{a} tini{a} 
0 packages upgraded, 19 newly installed, 0 to remove and 18 not upgraded.
Need to get 89.5 MB of archives. After unpacking 400 MB will be used.
The following packages have unmet dependencies:
 containerd.io : Conflicts: containerd but 1.4.3~ds1-1+b1 is to be installed
                 Conflicts: runc but 1.0.0~rc93+ds1-1 is to be installed
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     containerd [Not Installed]                         
2)     docker.io [Not Installed]                          
3)     runc [Not Installed]                               

     Leave the following dependencies unresolved:         
4)     docker-compose recommends docker.io (>= 1.9.0)     

The following NEW packages will be installed:
  containerd.io docker-compose libintl-perl{a} libintl-xs-perl{a} libmodule-find-perl{a} libmodule-scandeps-perl{a} libproc-processtable-perl{a} libsort-naturally-perl{a} needrestart{a} pigz{a} python3-cached-property{a} python3-docker{a} 
  python3-dockerpty{a} python3-docopt{a} 
The following packages are RECOMMENDED but will NOT be installed:
  docker.io 
0 packages upgraded, 14 newly installed, 0 to remove and 18 not upgraded.
Need to get 29.4 MB of archives. After unpacking 136 MB will be used.
Get: 1 https://download.docker.com/linux/debian stretch/stable amd64 containerd.io amd64 1.4.3-1 [28.1 MB]
Get: 2 http://kali.download/kali kali-rolling/main amd64 pigz amd64 2.5-1 [63.7 kB]  
Get: 3 http://kali.download/kali kali-rolling/main amd64 python3-cached-property all 1.5.2-1 [12.5 kB]
Get: 4 http://kali.download/kali kali-rolling/main amd64 python3-docker all 4.1.0-1.2 [85.2 kB]
Get: 5 http://kali.download/kali kali-rolling/main amd64 python3-dockerpty all 0.4.1-2 [11.1 kB]      
Get: 6 http://kali.download/kali kali-rolling/main amd64 python3-docopt all 0.6.2-3 [26.6 kB]
Get: 7 http://kali.download/kali kali-rolling/main amd64 docker-compose all 1.25.0-1 [119 kB]           
Get: 8 http://kali.download/kali kali-rolling/main amd64 libintl-perl all 1.26-2.1 [751 kB]
Get: 9 http://kali.download/kali kali-rolling/main amd64 libintl-xs-perl amd64 1.26-2.1 [39.8 kB]
Get: 10 http://kali.download/kali kali-rolling/main amd64 libmodule-find-perl all 0.15-1 [11.0 kB]
Get: 11 http://kali.download/kali kali-rolling/main amd64 libmodule-scandeps-perl all 1.30-1 [44.9 kB]
Get: 12 http://kali.download/kali kali-rolling/main amd64 libproc-processtable-perl amd64 0.59-2+b1 [45.9 kB]
Get: 13 http://kali.download/kali kali-rolling/main amd64 libsort-naturally-perl all 1.03-2 [13.5 kB]
Get: 14 http://kali.download/kali kali-rolling/main amd64 needrestart all 3.5-2 [61.9 kB]
Fetched 29.4 MB in 3s (10.9 MB/s)   
Selecting previously unselected package pigz.
(Reading database ... 364499 files and directories currently installed.)
Preparing to unpack .../00-pigz_2.5-1_amd64.deb ...
Unpacking pigz (2.5-1) ...
Selecting previously unselected package containerd.io.
Preparing to unpack .../01-containerd.io_1.4.3-1_amd64.deb ...
Unpacking containerd.io (1.4.3-1) ...
Selecting previously unselected package python3-cached-property.
Preparing to unpack .../02-python3-cached-property_1.5.2-1_all.deb ...
Unpacking python3-cached-property (1.5.2-1) ...
Selecting previously unselected package python3-docker.
Preparing to unpack .../03-python3-docker_4.1.0-1.2_all.deb ...
Unpacking python3-docker (4.1.0-1.2) ...
Selecting previously unselected package python3-dockerpty.
Preparing to unpack .../04-python3-dockerpty_0.4.1-2_all.deb ...
Unpacking python3-dockerpty (0.4.1-2) ...
Selecting previously unselected package python3-docopt.
Preparing to unpack .../05-python3-docopt_0.6.2-3_all.deb ...
Unpacking python3-docopt (0.6.2-3) ...
Selecting previously unselected package docker-compose.
Preparing to unpack .../06-docker-compose_1.25.0-1_all.deb ...
Unpacking docker-compose (1.25.0-1) ...
Selecting previously unselected package libintl-perl.
Preparing to unpack .../07-libintl-perl_1.26-2.1_all.deb ...
Unpacking libintl-perl (1.26-2.1) ...
Selecting previously unselected package libintl-xs-perl.
Preparing to unpack .../08-libintl-xs-perl_1.26-2.1_amd64.deb ...
Unpacking libintl-xs-perl (1.26-2.1) ...
Selecting previously unselected package libmodule-find-perl.
Preparing to unpack .../09-libmodule-find-perl_0.15-1_all.deb ...
Unpacking libmodule-find-perl (0.15-1) ...
Selecting previously unselected package libmodule-scandeps-perl.
Preparing to unpack .../10-libmodule-scandeps-perl_1.30-1_all.deb ...
Unpacking libmodule-scandeps-perl (1.30-1) ...
Selecting previously unselected package libproc-processtable-perl.
Preparing to unpack .../11-libproc-processtable-perl_0.59-2+b1_amd64.deb ...
Unpacking libproc-processtable-perl (0.59-2+b1) ...
Selecting previously unselected package libsort-naturally-perl.
Preparing to unpack .../12-libsort-naturally-perl_1.03-2_all.deb ...
Unpacking libsort-naturally-perl (1.03-2) ...
Selecting previously unselected package needrestart.
Preparing to unpack .../13-needrestart_3.5-2_all.deb ...
Unpacking needrestart (3.5-2) ...
Setting up python3-cached-property (1.5.2-1) ...
Setting up python3-docopt (0.6.2-3) ...
Setting up python3-docker (4.1.0-1.2) ...
Setting up libmodule-find-perl (0.15-1) ...
Setting up containerd.io (1.4.3-1) ...
containerd.service is a disabled or a static unit, not starting it.
Setting up libproc-processtable-perl (0.59-2+b1) ...
Setting up pigz (2.5-1) ...
Setting up libintl-perl (1.26-2.1) ...
Setting up libsort-naturally-perl (1.03-2) ...
Setting up libmodule-scandeps-perl (1.30-1) ...
Setting up python3-dockerpty (0.4.1-2) ...
Setting up needrestart (3.5-2) ...
Setting up docker-compose (1.25.0-1) ...
Setting up libintl-xs-perl (1.26-2.1) ...
Processing triggers for man-db (2.9.3-2) ...
Processing triggers for kali-menu (2021.1.4) ...
                                         
chown: cannot access '/var/run/docker.sock': No such file or directory

(snip)

**Comment by Ibrahimous** [comment]
Hi,
You're launching the script as root, which is VERY bad practice
Your error most probably comes from the fact that your docker installation failed, so that the interprocess file docker.soc has not been created
