### ISSUE TITLE
InvalidCursorName when attempting to perform an active scan

### ISSUE THREAD

**Issue by t94j0** [wavestone-cdt/abaddon#3]
When I fill out the information for performing an active scan, I get the rror:

```
Request Method: | POST
-- | --
http://68.183.118.79:8081/recon/active-scans/
2.2.10
InvalidCursorName
cursor "_django_curs_139792080627456_1" does not exist
/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py in execute_sql, line 1136
/usr/bin/python3
3.6.9
['/root/abaddon',  '/root/abaddon',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Mon, 2 Mar 2020 17:02:00 +0000
```

In the console, the error is:

```
django.db.utils.ProgrammingError: relation "reconnaissance_nmap" does not exist
LINE 1: ..."."SERVICE", "reconnaissance_nmap"."VERSION" FROM "reconnais...
```

I ran the setup/install.sh file successfully, so the DB tables should be created.

**Comment by Ibrahimous** [comment]
have you applied all migrations ?
If yes, could you try:

If Nmap scan refuse to works proprely

install nmaptocsv
sudo pip install nmaptocsv

Run syncdb to Fix the NMAP bug.
python3 manage.py migrate --run-syncdb

**Comment by Ibrahimous** [comment]
@t94j0 I'm closing the issue since this issue is a known one and since the above commands should fix it. Please reopen an issue or MP me on twitter if any further question.
